### ISSUE TITLE
電腦模擬器問題

### ISSUE THREAD

**Issue by Zhen-Bo** [McLaren12345/FGO_Bluetooth_Assistant#1]
請問這個能用在電腦模擬器上嗎?

**Comment by McLaren12345** [comment]
这个程序需要配合模块使用才行，无法使用模拟器。一开始开发的时候尝试过黑雷模拟器，但发现从模拟器截图存在黑屏问题，同时不支持模拟键盘控制，故使用了蓝牙鼠标进行控制。如果想尝试模拟器控制，需要修改Base_func与mouse文件中的函数，顶层的文件是通用的。





------------------ 原始邮件 ------------------
发件人: Zhen-Bo <notifications@github.com&gt;
发送时间: 2020年6月4日 13:46
收件人: McLaren12345/FGO_Bluetooth_Assistant <FGO_Bluetooth_Assistant@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[McLaren12345/FGO_Bluetooth_Assistant] 電腦模擬器問題 (#1)
