### ISSUE TITLE
关于蓝牙鼠标中发送数据包的问题

### ISSUE THREAD

**Issue by FallenTyrael** [McLaren12345/FGO_Bluetooth_Assistant#2]
原先脚本的数值在我这台测试手机上的点击有错位，研究了下源码中关于鼠标移动的部分，并在手机上测试了一下，横屏状态从左下角出发，发送08 00 A1 02 00 00 7F 00与08 00 A1 02 00 7F 00 00的数据包，在XY轴上，要达到屏幕边缘，发送数据包次数是一样的，想请问的是这里的鼠标移动数值对应的是哪一部分，是否和分辨率有关

**Comment by McLaren12345** [comment]
鼠标移动的数值就是数据帧中7F所在的位置，可以写00～FF（-128～+127）具体请参阅鼠标说明书中的数据格式。鼠标的具体移动距离与灵敏度有关，可以在设置里的触控设备中进行调节。





------------------ 原始邮件 ------------------
发件人: FallenTyrael <notifications@github.com&gt;
发送时间: 2020年9月26日 23:38
收件人: McLaren12345/FGO_Bluetooth_Assistant <FGO_Bluetooth_Assistant@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[McLaren12345/FGO_Bluetooth_Assistant] 关于蓝牙鼠标中发送数据包的问题 (#2)





 
原先脚本的数值在我这台测试手机上的点击有错位，研究了下源码中关于鼠标移动的部分，并在手机上测试了一下，横屏状态从左下角出发，发送08 00 A1 02 00 00 7F 00与08 00 A1 02 00 7F 00 00的数据包，在XY轴上，要达到屏幕边缘，发送数据包次数是一样的，想请问的是这里的鼠标移动数值对应的是哪一部分，是否和分辨率有关

**Comment by FallenTyrael** [comment]
鼠标移动的单位数值在XY轴上对应的距离好像并不一样。我测试过，从左下角触发，只进行X轴移动需要发送10次7F 00。在Y轴上移动也是发送10次00 7F

**Comment by McLaren12345** [comment]
是这样的，xy轴移动距离之比就是屏幕长宽之比





------------------ 原始邮件 ------------------
发件人: FallenTyrael <notifications@github.com&gt;
发送时间: 2020年9月27日 09:25
收件人: McLaren12345/FGO_Bluetooth_Assistant <FGO_Bluetooth_Assistant@noreply.github.com&gt;
抄送: McLaren <184086482@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[McLaren12345/FGO_Bluetooth_Assistant] 关于蓝牙鼠标中发送数据包的问题 (#2)





 
鼠标移动的单位数值在XY轴上对应的距离好像并不一样。我测试过，从左下角触发，只进行X轴移动需要发送10次7F 00。在Y轴上移动也是发送10次00 7F

**Comment by FallenTyrael** [comment]
是否可以这么理解，对于屏幕不同的设备，发送相同的数据包，鼠标移动距离不同。发送数据包中的数值是一个相对于当前分辨率百分比距离？

**Comment by McLaren12345** [comment]
是的，所以才需要测试修改驱动文件里的数值来适配不同手机和屏幕。





------------------ 原始邮件 ------------------
发件人: FallenTyrael <notifications@github.com&gt;
发送时间: 2020年9月27日 09:45
收件人: McLaren12345/FGO_Bluetooth_Assistant <FGO_Bluetooth_Assistant@noreply.github.com&gt;
抄送: McLaren <184086482@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[McLaren12345/FGO_Bluetooth_Assistant] 关于蓝牙鼠标中发送数据包的问题 (#2)





 
是否可以这么理解，对于屏幕不同的设备，发送相同的数据包，鼠标移动距离不同。

**Comment by FallenTyrael** [comment]
了解，感谢解答。后续关于蓝牙鼠标移动的多设备适配修改我会提交PR。不过这次无限池是赶不上了:(

**Comment by McLaren12345** [comment]
好的，非常感谢您的帮忙。我身边目前就一台手机，故一直没解决不同设备及系统的兼容性问题，如能实现定将署名感谢～





------------------ 原始邮件 ------------------
发件人: FallenTyrael <notifications@github.com&gt;
发送时间: 2020年9月27日 09:59
收件人: McLaren12345/FGO_Bluetooth_Assistant <FGO_Bluetooth_Assistant@noreply.github.com&gt;
抄送: McLaren <184086482@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[McLaren12345/FGO_Bluetooth_Assistant] 关于蓝牙鼠标中发送数据包的问题 (#2)





 
了解，感谢解答。后续关于蓝牙鼠标移动的多设备适配修改我会提交PR。不过这次无限池是赶不上了:(

**Comment by FallenTyrael** [comment]
在多个设备上测试了下，发送相同的数据包，每个设备鼠标移动的距离都有差别，暂时没发现普适性规律
